name: Docker Image CI

on:
  push:
    branches:
      - release_api

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.image-tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: generate image tag
      id: image-tag
      run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./api
        push: true
        tags: innfi/legendary-waddle:${{ github.sha }}

  deploy:
    needs: build
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.build.outputs.image-tag }}
      IMAGE_NAME: innfi/legendary-waddle

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          service: ${{ secrets.CLOUD_RUN_SERVICE }}
          region: ${{ secrets.GCP_REGION }}
          allow-unauthenticated: true
